"""Writes cptables.inc: DOS code page -> Unicode tables (from Python's codecs) for wsconv.
Run: python gencp.py"""
CPS = [437, 737, 775, 850, 852, 855, 857, 860, 861, 862, 863, 864, 865, 866, 869, 1125]

out = ['{ generated by gencp.py: bytes 80h-FFh of DOS code pages as Unicode (003Fh "?" where undefined) }',
       'const',
       '  CP_COUNT = %d;' % len(CPS),
       '  CP_NUMBERS: array[0..CP_COUNT - 1] of Word = (%s);' % ', '.join(map(str, CPS)),
       '  CP_HIGH: array[0..CP_COUNT - 1, $80..$FF] of Word = (']
for n, cp in enumerate(CPS):
    codes = []
    for b in range(0x80, 0x100):
        try:
            codes.append(ord(bytes([b]).decode('cp%d' % cp)))
        except UnicodeDecodeError:
            codes.append(0x3F)
    rows = ['      ' + ', '.join('$%04X' % c for c in codes[k:k + 16]) for k in range(0, 128, 16)]
    out.append('    ({ cp%d }\n%s)%s' % (cp, ',\n'.join(rows), ',' if n < len(CPS) - 1 else ''))
out.append('  );')
open('cptables.inc', 'w', newline='\n').write('\n'.join(out) + '\n')
print('cptables.inc: %d code pages' % len(CPS))
